# Tensores

Hemos visto:
* **escalares** (0 dimensiones)
* **vectores**  (1 dimensión)
* **matrices**  (2 dimensiones)

Cuando se requieren más de 2 dimensiones, se denominan **Tensores**

¿Python puede manejar tensores?  **Definitivamente Sí**

## Importar las librerías relevantes

In [2]:
import numpy as np

## Crear un tensor

In [3]:
matriz1 = np.array([[5,12,6],[-3,0,14]])
matriz1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
matriz2 = np.array([[9,8,7],[1,3,-5]])
matriz2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [5]:
tensor = np.array([matriz1,matriz2])
tensor

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Revisemos su forma

In [6]:
tensor.shape

(2, 2, 3)

## Creating de un tensor manualmente

In [7]:
tensor_manual = np.array([[[ 5, 12,  6], [-3,  0, 14]], [[ 9,  8,  7], [ 1,  3, -5]]])
tensor_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])