# Importar las librerías relevantes

In [1]:
import numpy as np

## Suma

In [4]:
matriz1 = np.array([[5,12,6],[-3,0,14]])
matriz1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
matriz2 = np.array([[9,8,7],[1,3,-5]])
matriz2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [6]:
matriz1 + matriz2

array([[14, 20, 13],
       [-2,  3,  9]])

## Resta

### Ejemplo 1

In [7]:
matriz3 = np.array([[5,3],[-2,4]])
matriz3

array([[ 5,  3],
       [-2,  4]])

In [8]:
matriz4 = np.array([[7,-5],[3,8]])
matriz4

array([[ 7, -5],
       [ 3,  8]])

In [9]:
matriz3 - matriz4

array([[-2,  8],
       [-5, -4]])

### Ejemplo 2

In [10]:
matriz5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
matriz5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [11]:
matriz6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
matriz6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [12]:
matriz5 - matriz6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Suma de vectores

In [13]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([5,4,3,2,1])

In [14]:
vector1 + vector2

array([6, 6, 6, 6, 6])

In [ ]:
vector1 - vector2