# Importar las librerías relevantes

In [4]:
import numpy as np

## Suma

### Suma de escalares

In [1]:
5 + 5

10

In [2]:
10 - 4

6

### Suma de matrices

In [5]:
matriz1 = np.array([[5,12,6],[-3,0,14]])
matriz1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
matriz3 = np.array([[5,3],[-2,4]])
matriz3

array([[ 5,  3],
       [-2,  4]])

In [7]:
matriz1 + matriz3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### Suma de vectores

In [8]:
vector1 = np.array([1,2,3,4,5])
vector1

array([1, 2, 3, 4, 5])

In [9]:
vector3 = np.array([1,2,3])
vector3

array([1, 2, 3])

In [10]:
vector1 + vector3

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

## La única condición es que los operandos deben tener las mismas dimensiones

Este es un requerimiento matemático. Sin embargo, con Python hay

### Excepciones (operaciones con un escalar)

In [11]:
matriz1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [12]:
matriz1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [13]:
vector1

array([1, 2, 3, 4, 5])

In [14]:
vector1 + 1

array([2, 3, 4, 5, 6])

In [15]:
matriz1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [16]:
vector1 + np.array([1])

array([2, 3, 4, 5, 6])

## Esto es un punto muy importante de recordar a la hora de programar!