# Importar las librerías relevantes

In [1]:
import numpy as np

## Transposición de matrices

Es buena práctica nombrar a las matrices con mayúsculas

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [5]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [6]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [7]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposición de escalares

In [8]:
escalar = np.array([5])

In [9]:
escalar.T

array([5])

Los escalares son muy aburridos:  escalar = escalar.T porque no tienen dimensión

## Transposición de vectores

In [11]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [12]:
vector.T

array([1, 2, 3])

No cambia porque los vectores son unidimensionales

In [13]:
vector.shape

(3,)

Sin embargo si convertimos al vector en bidimensional

In [16]:
vector_reformado = vector.reshape(1,3)
vector_reformado

array([[1, 2, 3]])

In [18]:
vector_reformado.shape

(1, 3)

In [17]:
vector_reformado.T

array([[1],
       [2],
       [3]])

In [19]:
vector_reformado.T.shape

(3, 1)

Ahora sí hay cambio